# Generated by Django 5.2.15 on 2026-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='max_downloads',
            field=models.IntegerField(default=1),
        ),
    ]
