# Generated by Django 5.2.15 on 2026-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_fileupload_download_count_fileupload_max_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
