# Generated by Django 5.2.15 on 2026-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_fileupload_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='expiry_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
