# Generated by Django 5.2.15 on 2026-07-18 11:04

import uploader.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_deletedupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='token',
            field=models.CharField(default=uploader.tokens.generate_token, max_length=100, unique=True),
        ),
    ]
